---
version: '3'

services:
  keeper:
    image: clickhouse/clickhouse-keeper:24.2-alpine
    container_name: keeper
    hostname: keeper
    volumes:
      - ./keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
  clickhouse01:
    image: clickhouse/clickhouse-server:24.2
    container_name: clickhouse01
    hostname: clickhouse01
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./config.d:/etc/clickhouse-server/config.d
    depends_on:
      - keeper
    environment:
      CLICKHOUSE_SHARD: 1
      CLICKHOUSE_REPLICA: 1
      CLICKHOUSE_DB: "${CLICKHOUSE_DB:-test}"
  clickhouse02:
    image: clickhouse/clickhouse-server:24.2
    container_name: clickhouse02
    hostname: clickhouse02
    volumes:
      - ./config.d:/etc/clickhouse-server/config.d
    depends_on:
      - keeper
    environment:
      CLICKHOUSE_SHARD: 2
      CLICKHOUSE_REPLICA: 1
      CLICKHOUSE_DB: "${CLICKHOUSE_DB:-test}"
